In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

In [3]:
df=pd.read_csv('Titanic_dataset_kaggle.csv',usecols=['Age','Fare','Survived'])

In [4]:
df.head()

,Survived,Age,Fare
0,0,34.5,7.8292
1,1,47.0,7.0000
2,0,62.0,9.6875
3,0,27.0,8.6625
4,1,22.0,12.2875


In [5]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [7]:
x_train.head()

,Age,Fare
280,23.0,8.6625
284,2.0,20.2125
40,39.0,13.4167
17,21.0,7.2250
362,31.0,21.0000


In [9]:
si=SimpleImputer()
x_train_trf=si.fit_transform(x_train)
x_test_trf=si.transform(x_test)

In [10]:
x_train_trf

array([[2.30000000e+01, 8.66250000e+00],
       [2.00000000e+00, 2.02125000e+01],
       [3.90000000e+01, 1.34167000e+01],
       [2.10000000e+01, 7.22500000e+00],
       [3.10000000e+01, 2.10000000e+01],
       [8.00000000e+00, 2.60000000e+01],
       [2.93072519e+01, 7.00000000e+00],
       [3.70000000e+01, 8.31583000e+01],
       [1.70000000e+01, 4.71000000e+01],
       [3.10000000e+01, 2.10000000e+01],
       [8.30000000e-01, 9.35000000e+00],
       [2.93072519e+01, 2.65500000e+01],
       [2.20000000e+01, 8.96250000e+00],
       [2.93072519e+01, 2.16792000e+01],
       [2.70000000e+01, 7.89580000e+00],
       [2.10000000e+01, 7.85420000e+00],
       [4.50000000e+01, 6.33583000e+01],
       [2.20000000e+01, 1.05000000e+01],
       [2.93072519e+01, 2.10000000e+01],
       [3.20000000e+01, 7.57920000e+00],
       [2.93072519e+01, 1.45000000e+01],
       [2.50000000e+01, 2.60000000e+01],
       [2.60000000e+01, 2.20250000e+01],
       [2.50000000e+01, 5.54417000e+01],
       [2.930725

In [11]:
from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()
clf.fit(x_train_trf,y_train)
y_pred=clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6428571428571429

In [12]:
mi=MissingIndicator()
mi.fit(x_train)

MissingIndicator()

In [13]:
mi.features_

array([0, 1], dtype=int64)

In [15]:
x_train_missing = mi.transform(x_train)

In [17]:
x_train_missing

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [Fal

In [19]:
x_test_missing = mi.transform(x_test)

In [20]:
x_test_missing

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [Fal

In [22]:
x_train['Age_NA'] = x_train['Age'].isnull().astype(int)

In [24]:
x_test

,Age,Fare
146,NaN,51.8625
223,21.0,7.7958
193,61.0,12.3500
305,64.0,26.5500
188,NaN,69.5500
...,...,...
348,24.0,13.5000
30,50.0,26.0000
174,40.0,31.3875
68,31.0,28.5375


In [26]:
x_test['Age_NA'] = x_test['Age'].isnull().astype(int)

In [28]:

x_train


,Age,Fare,Age_NA
280,23.0,8.6625,0
284,2.0,20.2125,0
40,39.0,13.4167,0
17,21.0,7.2250,0
362,31.0,21.0000,0
...,...,...,...
299,29.0,7.8542,0
22,NaN,31.6833,1
72,29.0,7.9250,0
15,24.0,27.7208,0


In [30]:

si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [33]:

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf2,y_train)

y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6428571428571429

In [34]:
si = SimpleImputer(add_indicator=True)

In [37]:

x_train = si.fit_transform(x_train)

In [39]:
x_test = si.transform(x_test)

In [42]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf2,y_train)

y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6428571428571429